import { library } from "@fortawesome/fontawesome-svg-core";
import { FontAwesomeIcon } from "@fortawesome/vue-fontawesome";
import {
  faEyeSlash,
  faSquarePlus,
  faEye,
  faSquareCheck,
  faSquare,
  faPenToSquare,
  faFolderOpen,
  faFile,
  faUser,
  faCircleDown
} from "@fortawesome/free-regular-svg-icons";

import {
  faUsers,
  faFileArrowUp,
  faFileLines,
  faArrowUpFromBracket,
  faTrashCan,
  faCircleCheck,
  faPlus,
  faCircleArrowUp,
  faCircleArrowDown,
  faTriangleExclamation,
  faCloudArrowUp,
  faMagnifyingGlass,
  faGlobe,
  faLock,
  faLockOpen,
  faClockRotateLeft,
  faHouseUser,
  faChevronRight,
  faChevronLeft,
  faSignInAlt,
  faXmark,
  faGear,
  faWrench,
  faUnlock
} from "@fortawesome/free-solid-svg-icons";

library.add(
    faUsers,
    faFileArrowUp,
    faFileLines,
    faArrowUpFromBracket,
    faTrashCan,
    faCircleCheck,
    faPlus,
    faCircleArrowUp,
    faCircleArrowDown,
    faTriangleExclamation,
    faCloudArrowUp,
    faSquarePlus,
    faMagnifyingGlass,
    faGlobe,
    faLock,
    faLockOpen,
    faClockRotateLeft,
    faHouseUser,
    faChevronRight,
    faChevronLeft,
    faSignInAlt,
    faEyeSlash,
    faEye,
    faXmark,
    faSquareCheck,
    faSquare,
    faPenToSquare,
    faGear,
    faFolderOpen,
    faFile,
    faUser,
    faWrench,
    faCircleDown,
    faUnlock
  );

  export { FontAwesomeIcon };